# Generated by Django 6.0.7 on 2026-07-22 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_empleado', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
                ('presupuesto_estimado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_actual', models.CharField(choices=[('NUEVO', 'nuevo'), ('CONTACTADO', 'contactado'), ('NEGOCIACION', 'negociacion'), ('GANADO', 'ganado'), ('PERDIDO', 'perdido')], default='NUEVO', max_length=100)),
                ('es_corporativo', models.BooleanField(default=False)),
                ('prioridad', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], max_length=10)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='api.vendedor')),
            ],
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, max_length=100)),
                ('estado_nuevo', models.CharField(max_length=100)),
                ('notas', models.TextField(blank=True)),
                ('fecha_evento', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bitacora', to='api.lead')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bitacora', to='api.vendedor')),
            ],
        ),
    ]
